stages:
  - build
  - deploy

build job:
  stage: build
  script:
    - export PYTHONPATH=.
    - export FLASK_APP=web
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip

deploy job:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install curl -y
    - curl http://localhost:8000/widgets